HisakaWeb/Controllers/CartController.cs
using HisakaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HisakaWeb.Controllers
{
    public class CartController : Controller
    {
        private HisakaDBEntities db = new HisakaDBEntities();

        // GET: Cart
        public ActionResult Index()
        {
            // Retrieve cart items from session
            List<Cart> cartItems = Session["CartItems"] as List<Cart> ?? new List<Cart>();
            return View(cartItems);
        }

        public ActionResult AddToCart(string productId)
        {
            // Check if the user is logged in (Session["Username"] is not null)
            if (Session["Username"] != null)
            {
                Product product = db.Products.Find(productId);

                if (product == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    // Retrieve cart items from session
                    List<Cart> cartItems = Session["CartItems"] as List<Cart> ?? new List<Cart>();

                    // Check if the product is already in the cart
                    Cart existingItem = cartItems.FirstOrDefault(item => item.productId == productId);

                    if (existingItem != null)
                    {
                        // If the product is already in the cart, increment the quantity
                        existingItem.productQuantity += 1;
                    }
                    else
                    {
                        // If the product is not in the cart, add a new cart item
                        Cart cartItem = new Cart(product.productID, product.productName, (double)product.productPrice, 1, product.productImage);
                        cartItems.Add(cartItem);
                    }

                    // Save the updated cart items to session
                    Session["CartItems"] = cartItems;

                    return RedirectToAction("Index");
                }
            }
            else
            {
                // Redirect to a login page or show a message indicating that the user needs to log in.
                return RedirectToAction("Login", "Home"); // Change the action and controller names accordingly.
            }
        }


        public ActionResult RemoveFromCart(string productId)
        {
            // Retrieve cart items from session
            List<Cart> cartItems = Session["CartItems"] as List<Cart> ?? new List<Cart>();

            // Find the item to be removed
            Cart itemToRemove = cartItems.FirstOrDefault(item => item.productId == productId);

            if (itemToRemove != null)
            {
                // If the quantity is greater than 1, decrement the quantity
                if (itemToRemove.productQuantity > 1)
                {
                    itemToRemove.productQuantity -= 1;
                }
                else
                {
                    // If the quantity is 1 or less, remove the item from the cart
                    cartItems.Remove(itemToRemove);
                }

                // Save the updated cart items to session
                Session["CartItems"] = cartItems;
            }

            // Redirect back to Index
            return RedirectToAction("Index", cartItems);
        }

        public ActionResult TotalCart()
        {
            // Retrieve cart items from session
            List<Cart> cartItems = Session["CartItems"] as List<Cart> ?? new List<Cart>();

            if(cartItems == null)
            {
                ViewBag.Total = 0;
                return View("Index");
            }

            // Calculate the total price
            double total = cartItems.Sum(item => item.productPrice * item.productQuantity);

            // Pass the total to the view
            ViewBag.Total = total;

            // Return a view to display the total
            return View("Index", cartItems);
        }
    }
}

HisakaWeb/Controllers/ProductDetailController.cs
using HisakaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HisakaWeb.Controllers
{
    public class ProductDetailController : Controller
    {
        private HisakaDBEntities db = new HisakaDBEntities();

        // GET: Products/Details/5
        public ActionResult Index(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            // Lấy danh sách sản phẩm
            var relatedProduct = db.Products.Where(p => p.productBrand == product.productBrand || p.productCategory == product.productCategory).ToList();

            ViewBag.relatedProduct = relatedProduct;

            var productCates = db.Products.Where(p => p.productCategory == product.productCategory).ToList();

            ViewBag.sameCate = productCates;

            return View(product);
        }
    }
}

HisakaWeb/Controllers/ProductListController.cs
using HisakaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HisakaWeb.Controllers
{
    public class ProductListController : Controller
    {
        private HisakaDBEntities db = new HisakaDBEntities();

        // GET: ProductList
        public ActionResult Index(double? max, double? min)
        {           
            // Xử lý logic sắp xếp sản phẩm theo giá ở đây
            // Sử dụng các tham số min và max để áp dụng bộ lọc theo giá

            // Ví dụ: sắp xếp theo giá tăng dần
            var sortedProducts = db.Products.ToList();

            ViewBag.sideProducts = db.Products.ToList();

            // Nếu max có giá trị, áp dụng bộ lọc giá trị tối đa
            if (max.HasValue)
            {
                sortedProducts = sortedProducts.Where(p => p.productPrice <= max.Value).ToList();
            }

            if (min.HasValue)
            {
                // Áp dụng bộ lọc giá trị tối thiểu
                sortedProducts = sortedProducts.Where(p => p.productPrice >= min).ToList();
            }
            // Trả về view hoặc làm cái gì đó với sortedProducts ở đây
            return View(sortedProducts);
        }

    }
}

HisakaWeb/Views/ProductList/Index.cshtml
@model IEnumerable<HisakaWeb.Models.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Products</a></li>
            <li class="breadcrumb-item active">Product List</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Product List Start -->
<div class="product-view">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-md-12">
                        <div class="product-view-top">
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="product-search">
                                        <input type="email" placeholder="Search">
                                        <button><i class="fa fa-search"></i></button>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="product-price-range">
                                        <div class="dropdown">
                                            <div class="dropdown-toggle" data-toggle="dropdown">Product price range</div>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="@Url.Action("Index", "ProductList", new {min = 0, max = 99999})" class="dropdown-item">0 VND to 99,999 VND</a>
                                                <a href="@Url.Action("Index", "ProductList", new {min = 100000, max = 199999})" class="dropdown-item">100,000 VND to 199,999 VND</a>
                                                <a href="@Url.Action("Index", "ProductList", new {min = 200000, max = 299999})" class="dropdown-item">200,000 VND to 299,000 VND</a>
                                                <a href="@Url.Action("Index", "ProductList", new {min = 300000})" class="dropdown-item">From 300,000 VND</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @foreach (var item in Model)
                    {
                        <div class="col-md-4">
                            <div class="product-item">
                                <div class="product-title">
                                    <a href="#">@item.productName</a>
                                    <div class="ratting">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                </div>
                                <div class="product-image">
                                    <a href="product-detail.html">
                                        <img src="@item.productImage" alt="Product Image" height="500" />
                                    </a>
                                    <div class="product-action">
                                        <a href="#"><i class="fa fa-cart-plus"></i></a>
                                        <a href="@Url.Action("Index","ProductDetail", new { id=item.productID })"><i class="fa fa-search"></i></a>
                                    </div>
                                </div>
                                @{
                                    double price = (double)item.productPrice;
                                }
                                <div class="product-price">
                                    <h3>@price.ToString("#,##0 VND")</h3>
                                    <a class="btn" href="@Url.Action("AddToCart", "Cart", new { productId = item.productID })"><i class="fa fa-shopping-cart"></i>Add to Cart</a>
                                </div>
                            </div>
                         </div>
                    }

                </div>

                <!-- Pagination Start -->
                <div class="col-md-12">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!-- Pagination Start -->
            </div>

            <!-- Side Bar Start -->
            <div class="col-lg-4 sidebar">
                <div class="sidebar-widget category">
                    <h2 class="title">Category</h2>
                    <nav class="navbar bg-light">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-female"></i>Fashion & Beauty</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-child"></i>Kids & Babies Clothes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-tshirt"></i>Men & Women Clothes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-mobile-alt"></i>Gadgets & Accessories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-microchip"></i>Electronics & Accessories</a>
                            </li>
                        </ul>
                    </nav>
                </div>

                <div class="sidebar-widget widget-slider">
                    <div class="sidebar-slider normal-slider">
                        @foreach (var sideProduct in ViewBag.sideProducts)
                        {
                            <div class="product-item">
                                <div class="product-title" style="overflow:hidden">
                                    <a href="#">@sideProduct.productName</a>
                                    <div class="ratting">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                </div>
                                <div class="product-image">
                                    <a href="product-detail.html">
                                        <img src="@sideProduct.productImage" alt="Product Image" height="500" />
                                    </a>
                                    <div class="product-action">
                                        <a href="#"><i class="fa fa-cart-plus"></i></a>
                                        <a href="@Url.Action("Index","ProductDetail", new { id=sideProduct.productID })"><i class="fa fa-search"></i></a>
                                    </div>
                                </div>
                                @{
                                    double price = (double)sideProduct.productPrice;
                                }
                                <div class="product-price">
                                    <h3>@price.ToString("#,##0 VND")</h3>
                                    <a class="btn" href="@Url.Action("AddToCart", "Cart", new { productId = sideProduct.productID })"><i class="fa fa-shopping-cart"></i>Add to Cart</a>
                                </div>
                            </div>
                        }

                    </div>
                </div>

                <div class="sidebar-widget brands">
                    <h2 class="title">Our Brands</h2>
                    <ul>
                        <li><a href="#">Nulla </a><span>(45)</span></li>
                        <li><a href="#">Curabitur </a><span>(34)</span></li>
                        <li><a href="#">Nunc </a><span>(67)</span></li>
                        <li><a href="#">Ullamcorper</a><span>(74)</span></li>
                        <li><a href="#">Fusce </a><span>(89)</span></li>
                        <li><a href="#">Sagittis</a><span>(28)</span></li>
                    </ul>
                </div>

                <div class="sidebar-widget tag">
                    <h2 class="title">Tags Cloud</h2>
                    <a href="#">Lorem ipsum</a>
                    <a href="#">Vivamus</a>
                    <a href="#">Phasellus</a>
                    <a href="#">pulvinar</a>
                    <a href="#">Curabitur</a>
                    <a href="#">Fusce</a>
                    <a href="#">Sem quis</a>
                    <a href="#">Mollis metus</a>
                    <a href="#">Sit amet</a>
                    <a href="#">Vel posuere</a>
                    <a href="#">orci luctus</a>
                    <a href="#">Nam lorem</a>
                </div>
            </div>
            <!-- Side Bar End -->
        </div>
    </div>
</div>
<!-- Product List End -->