HisakaWeb/Models/Brand.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HisakaWeb.Models
{
    public partial class Brand
    {
        public Brand()
        {
            this.Products = new HashSet<Product>();
        }

        [Required(ErrorMessage = "Brand Name is required")]
        [StringLength(20, ErrorMessage = "Brand Name must be at most 20 characters")]
        public string brandName { get; set; }

        public string brandLogo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

HisakaWeb/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HisakaWeb.Models;

namespace HisakaWeb.Controllers
{
    public class BrandsController : Controller
    {
        private HisakaDBEntities db = new HisakaDBEntities();

        // GET: Brands
        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        // GET: Brands/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: Brands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "brandName,brandLogo")] Brand brand)
        {
            if (brand.brandLogo == null)
            {
                ModelState.AddModelError("brandLogo", "Please select a brand logo.");
                return View(brand);
            }
            if (ModelState.IsValid)
            {
                var urlTuongDoi = "/Content/img/brands_logo/";

                brand.brandLogo = urlTuongDoi + brand.brandLogo;

                // Add the brand to the database and save changes
                db.Brands.Add(brand);
                db.SaveChanges();

                // Redirect to the Index action
                return RedirectToAction("Index");
            }

            // Return the View with the brand object if validation fails
            return View(brand);
        }


        // GET: Brands/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "brandName,brandLogo")] Brand brand)
        {
            if (brand.brandLogo == null)
            {
                ModelState.AddModelError("brandLogo", "Please select a brand logo.");
                return View(brand);
            }
            if (ModelState.IsValid)
            {
                var urlTuongDoi = "/Content/img/brands_logo/";

                brand.brandLogo = urlTuongDoi + brand.brandLogo;

                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: Brands/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HisakaWeb/Views/Brands/Create.cshtml
@model HisakaWeb.Models.Brand

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index")">Categories</a></li>
                    <li class="breadcrumb-item active">Create Brands</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<section class="content">
    <h2 class="col-md-3">Thêm nhãn hàng mới</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.brandName, "Nhãn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.brandName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.brandName, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.brandLogo, "Logo nhãn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.brandLogo, new { htmlAttributes = new {  @type = "file" } })
                    @Html.ValidationMessageFor(model => model.brandLogo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                    <a href="@Url.Action("Index")" class="btn btn-default">Trở lại trang chính</a>
                </div>
            </div>
        </div>
    }
</section>

HisakaWeb/Views/Brands/Delete.cshtml
@model HisakaWeb.Models.Brand

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index")">Categories</a></li>
                    <li class="breadcrumb-item active">Delete Brands</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<section class="content">
    <h2 class="col-md-3">Xóa nhãn hàng </h2>
    <span class="col-md-3 text-warning">Bạn có chắc chắn muốn xóa nhãn hàng này?</span>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.brandName, "Nhãn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.brandName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.brandName, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.brandLogo, "Logo nhãn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img src="@Html.DisplayFor(model => model.brandLogo)" width="200" />
                    <br />
                    @Html.ValidationMessageFor(model => model.brandLogo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <a href="@Url.Action("Index")" class="btn btn-default">Trở lại trang chính</a>
                </div>
            </div>
        </div>
    }
</section>

HisakaWeb/Views/Brands/Details.cshtml
@model HisakaWeb.Models.Brand

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.brandLogo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brandLogo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.brandName }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HisakaWeb/Views/Brands/Edit.cshtml
@model HisakaWeb.Models.Brand

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index")">Categories</a></li>
                    <li class="breadcrumb-item active">Edit Brands</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<section class="content">
    <h2 class="col-md-3">Chỉnh sửa nhãn hàng </h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.brandName, "Nhãn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.brandName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.brandName, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.brandLogo, "Logo nhãn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img src="@Html.DisplayFor(model => model.brandLogo)" width="200" />
                    <br />
                    <input type="file" id="brandLogo" name="brandLogo" />
                    @Html.ValidationMessageFor(model => model.brandLogo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Edit" class="btn btn-info" />
                    <a href="@Url.Action("Index")" class="btn btn-default">Trở lại trang chính</a>
                </div>
            </div>
        </div>
    }
</section>

HisakaWeb/Views/Brands/Index.cshtml
@model IEnumerable<HisakaWeb.Models.Brand>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>

    .crud-btn {
        display: inline-block;
        width: 40px;
        height: 40px;
        border-radius: 100%;
    }

        .crud-btn i {
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 100%;
        }

    td, th {
        text-align: center;
    }
</style>

@{
    int count = 0;
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Brands</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<section class="content">
    <div class="card">
        <div class="card-header border-transparent">
            <h3 class="card-title">Danh sách nhãn hàng</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table m-0">
                    <thead>
                        <tr>
                            <th>Số thứ tự</th>
                            <th>Nhãn hàng</th>
                            <th>Logo nhãn hàng</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            count++;
                        <tr>
                            <td>@count</td>
                            <td>@Html.DisplayFor(modelItem => item.brandName)</td>
                            <td><img src="@Html.DisplayFor(modelItem => item.brandLogo)" width="200"/></td>

                            <td>
                                <a href="@Url.Action("Edit","Brands", new { id=item.brandName })" class="crud-btn btn-info">
                                    <i class="fa-solid fa-pen-to-square">
                                    </i>
                                </a>
                                <a href="@Url.Action("Delete","Brands", new { id=item.brandName })" class="crud-btn btn-danger">
                                    <i class="fa-solid fa-x">
                                    </i>
                                </a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.card-body -->
        <div class="card-footer clearfix">
            <a href="@Url.Action("Create", "Brands")" class="btn btn-sm btn-success float-left">Thêm nhãn hàng mới</a>
        </div>
        <!-- /.card-footer -->
    </div>
</section>